spring:  application:    name: product-service  datasource:    url: jdbc:mysql://localhost:3306/productmanage?useSSL=false    username: root    password: Jun07@dbs.com  jpa:    properties:      hibernate:        dialect: org.hibernate.dialect.MySQL5InnoDBDialect        format_sql: true    hibernate:      ddl-auto: update    show-sql: true  config:    import: configserver:http://localhost:8888  profiles:    active: dev    
server:
  port: 8098
  
eureka:  instance:    hostname: localhost    lease-renewal-interval-in-seconds: 10    lease-expiration-duration-in-seconds: 20    prefer-ip-address: true
  client:
    service-url:      defaultZone: http://localhost:8761/eureka
    healthcheck:      enabled: false
 
logging:  level:    com.handson.ps.dev: INFO