
server:  port: 8888
  
spring:
  application:
    name: Product-Config-Server-local  cloud:    config:      server:        git:          uri: file:/F:/eclipse-workspace-spring/HandsonDay7/cs-properties-repo
          clone-on-start: true

  security:    user:      name: root
      password: root123